# Generated by Django 4.0.2 on 2022-03-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_tag_scopes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
