# Generated by Django 4.0.2 on 2022-04-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='id_sensor',
        ),
        migrations.AddField(
            model_name='measurement',
            name='id_sensor',
            field=models.ManyToManyField(to='measurement.Sensor'),
        ),
    ]
